Now works on pre-eip-4895 blocks
0xPolygonZero/zero-bin pull request #45
Opened 2024-03-27 19:39 UTC by BGluth

- This EIP added `withdrawals` which added the `withdrawal` field to the `zeroTracer` payload. The decoder always expected this field to be present, but now just uses an empty withdrawal vec in the case that this is missing.

2024-03-28 00:39 UTC, Nashtare approved these changes

2024-03-28 00:41 UTC, Nashtare requested changes
Sorry I misclicked, I didn't mean to approve.
I think we'd need to be careful with this, as some other EIPs part of Shanghai upgrade do change the logic that the prover replicates / expects, which could mess up post-Merge / pre-Shanghai blocks.

2024-03-28 02:51 UTC, BGluth commented
Makes sense. Lets hold off for now.

2024-05-03 12:38 UTC, Nashtare commented
@BGluth I don't remember the motivation behind this PR. What should we do about it?

2024-05-07 21:14 UTC, Nashtare commented
Closing as per offline discussion.

2024-05-07 21:14 UTC, closed without merging